import type {Game} from '../data/library';
export function normaliseMiSTerRemoteUrl(value:string){const raw=value.trim().replace(/\/+$/,'');if(!raw)throw new Error('Enter your MiSTer address.');const candidate=/^https?:\/\//i.test(raw)?raw:`http://${raw}`;const parsed=new URL(candidate);if(!parsed.hostname)throw new Error('Enter a valid MiSTer address.');return `http://${parsed.hostname}:8182/api`;}
const computerLoaders=new Set(['c64','commodore64','spectrum','zxspectrum','sinclairzxspectrum']);
const systemKey=(value?:string)=>value?.toLowerCase().replace(/[^a-z0-9]+/g,'')??'';
export function launchRoutesFor(game:Pick<Game,'remoteSystemId'>){return computerLoaders.has(systemKey(game.remoteSystemId))?['/games/launch','/launch']:['/launch'];}
export function isC64TapeImage(game:Pick<Game,'remoteFilePath'|'remoteSystemId'>){return ['c64','commodore64'].includes(systemKey(game.remoteSystemId))&&/\.t64$/i.test(game.remoteFilePath??'');}
export function c64TapeLoadCommands(){return [38,24,30,32,28].map(code=>`kbdRaw:${code}`);}
function remoteWebSocketUrl(value:string){return normaliseMiSTerRemoteUrl(value).replace(/^http/i,'ws')+'/ws';}
function sendRemoteCommands(value:string,commands:string[]){return new Promise<void>((resolve,reject)=>{const socket=new WebSocket(remoteWebSocketUrl(value));const openTimeout=setTimeout(()=>{socket.close();reject(new Error('MiSTer Remote keyboard connection timed out.'));},4000);let index=0;const sendNext=()=>{if(index>=commands.length){clearTimeout(openTimeout);socket.close();resolve();return;}socket.send(commands[index++]);setTimeout(sendNext,180);};socket.onopen=()=>{clearTimeout(openTimeout);sendNext();};socket.onerror=()=>{clearTimeout(openTimeout);reject(new Error('MiSTer Remote could not send the C64 tape load command.'));};});}
function startC64Tape(value:string){setTimeout(()=>{void sendRemoteCommands(value,c64TapeLoadCommands()).catch(()=>{});},2800);}
export async function launchMiSTerRemoteGame(value:string,game:Pick<Game,'remoteFilePath'|'remoteSystemId'>){if(!game.remoteFilePath)throw new Error('This game has no launch path in the MiSTer library.');const path=game.remoteFilePath;const folderMatch=path.match(/\/games\/([^/]+)\/(.+)$/i);const payload={path,...(game.remoteSystemId?{system:game.remoteSystemId}:{}),...(folderMatch?{gamePath:folderMatch[2],systemFolder:folderMatch[1]}:{})};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{let response:Response|undefined;for(const route of launchRoutesFor(game)){response=await fetch(`${normaliseMiSTerRemoteUrl(value)}${route}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});if(response.ok||response.status!==404)break;}if(!response?.ok)throw new Error(`MiSTer Remote could not launch the game (HTTP ${response?.status??'unknown'}).`);if(isC64TapeImage(game))startC64Tape(value);}catch(error){if(error instanceof DOMException&&error.name==='AbortError')throw new Error('MiSTer Remote timed out. Check that Remote is running on your MiSTer.');if(error instanceof TypeError)throw new Error('Could not reach MiSTer Remote on port 8182.');throw error;}finally{clearTimeout(timer);}}
